name: todo1
description: A starting point for Dart libraries or applications.
version: 1.0.0
#repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-194.0.dev

# Add regular dependencies here.
dependencies:
  material_design_icons_flutter: ^7.0.7296
  path: ^1.8.0
  flutter:

    sdk: flutter
    # This line should be indented under 'flutter:'
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0

  flutter_launcher_icons: ^0.14.1

flutter_icons:
  image_path: assets/icon13.png
  android: true
  ios: true